// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloDb;

namespace ModeloDb.Migrations
{
    [DbContext(typeof(DbConsecionaria))]
    [Migration("20220128035345_finalpro")]
    partial class finalpro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConcesionarioV.Entidades.DatosCliente", b =>
                {
                    b.Property<int>("DatosClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres_Completos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("DatosClienteId");

                    b.ToTable("DatosClientes");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.Distribuidora", b =>
                {
                    b.Property<int>("DistribuidoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Distribuidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Unidades")
                        .HasColumnType("int");

                    b.HasKey("DistribuidoraId");

                    b.ToTable("Distribuidoras");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.FacturaDistribuidora", b =>
                {
                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<int>("DistribuidoraId")
                        .HasColumnType("int");

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventarioId", "DistribuidoraId");

                    b.HasIndex("DistribuidoraId");

                    b.ToTable("FacturaDistribuidoras");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.InformeGasto", b =>
                {
                    b.Property<int>("InformeGastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Agua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatosClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Luz")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Otros_servicios")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Telefono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InformeGastoId");

                    b.HasIndex("DatosClienteId")
                        .IsUnique();

                    b.ToTable("InformeGastos");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.IngresoNeto", b =>
                {
                    b.Property<int>("IngresoNetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InformeGastoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Ingresos_Totales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RolPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rol_Pagos_Netos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Servicios_Basicos_Netos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_Aprobacion")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IngresoNetoId");

                    b.HasIndex("InformeGastoId");

                    b.HasIndex("RolPagoId");

                    b.ToTable("IngresoNetos");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.Inventario", b =>
                {
                    b.Property<int>("InventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio_por_unidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Unidades")
                        .HasColumnType("int");

                    b.HasKey("InventarioId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.ResumenAmortizacion", b =>
                {
                    b.Property<int>("ResumenAmortizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IngresoNetoId")
                        .HasColumnType("int");

                    b.Property<string>("Prestamo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SumaCuotas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SumaInteres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TablaAmortizacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrestamo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ResumenAmortizacionId");

                    b.HasIndex("IngresoNetoId");

                    b.HasIndex("TablaAmortizacionId");

                    b.ToTable("ResumenAmortizacions");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.RolPago", b =>
                {
                    b.Property<int>("RolPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Anticipos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AporteIEES")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DatosClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Horas_extra")
                        .HasColumnType("int");

                    b.Property<decimal>("Sueldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RolPagoId");

                    b.HasIndex("DatosClienteId");

                    b.ToTable("RolPagos");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.TablaAmortizacion", b =>
                {
                    b.Property<int>("TablaAmortizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Años")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteresEquivalente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCuotas")
                        .HasColumnType("int");

                    b.Property<int>("Numeropagos")
                        .HasColumnType("int");

                    b.Property<string>("TNA30_360")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorPrestamo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TablaAmortizacionId");

                    b.HasIndex("InventarioId");

                    b.ToTable("TablaAmortizacions");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.FacturaDistribuidora", b =>
                {
                    b.HasOne("ConcesionarioV.Entidades.Distribuidora", "Distribuidoras")
                        .WithMany("FacturaDistribuidoras")
                        .HasForeignKey("DistribuidoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConcesionarioV.Entidades.Inventario", "Inventarios")
                        .WithMany("FacturaDistribuidoras")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribuidoras");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.InformeGasto", b =>
                {
                    b.HasOne("ConcesionarioV.Entidades.DatosCliente", "DatosClientes")
                        .WithOne("InformeGastos")
                        .HasForeignKey("ConcesionarioV.Entidades.InformeGasto", "DatosClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosClientes");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.IngresoNeto", b =>
                {
                    b.HasOne("ConcesionarioV.Entidades.InformeGasto", "InformeGastos")
                        .WithMany("IngresoNetos")
                        .HasForeignKey("InformeGastoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConcesionarioV.Entidades.RolPago", "RolPagos")
                        .WithMany("IngresoNetos")
                        .HasForeignKey("RolPagoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InformeGastos");

                    b.Navigation("RolPagos");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.ResumenAmortizacion", b =>
                {
                    b.HasOne("ConcesionarioV.Entidades.IngresoNeto", "IngresoNetos")
                        .WithMany("ResumenAmortizacions")
                        .HasForeignKey("IngresoNetoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConcesionarioV.Entidades.TablaAmortizacion", "TablaAmortizacions")
                        .WithMany("ResumenAmortizacions")
                        .HasForeignKey("TablaAmortizacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IngresoNetos");

                    b.Navigation("TablaAmortizacions");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.RolPago", b =>
                {
                    b.HasOne("ConcesionarioV.Entidades.DatosCliente", "DatosClientes")
                        .WithMany("RolPagos")
                        .HasForeignKey("DatosClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosClientes");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.TablaAmortizacion", b =>
                {
                    b.HasOne("ConcesionarioV.Entidades.Inventario", "Inventarios")
                        .WithMany("tablaAmortizacions")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.DatosCliente", b =>
                {
                    b.Navigation("InformeGastos");

                    b.Navigation("RolPagos");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.Distribuidora", b =>
                {
                    b.Navigation("FacturaDistribuidoras");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.InformeGasto", b =>
                {
                    b.Navigation("IngresoNetos");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.IngresoNeto", b =>
                {
                    b.Navigation("ResumenAmortizacions");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.Inventario", b =>
                {
                    b.Navigation("FacturaDistribuidoras");

                    b.Navigation("tablaAmortizacions");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.RolPago", b =>
                {
                    b.Navigation("IngresoNetos");
                });

            modelBuilder.Entity("ConcesionarioV.Entidades.TablaAmortizacion", b =>
                {
                    b.Navigation("ResumenAmortizacions");
                });
#pragma warning restore 612, 618
        }
    }
}
